presentation1.pdf: presentation1.md
	# requires Latex, Pandoc, and the Eisvogel template https://github.com/Wandmalfarbe/pandoc-latex-template
	pandoc presentation1.md --output presentation1.pdf --from markdown --to beamer --template "eisvogel.latex"